version: "3"
services: 
    agent:
        image:
            image: portainer/agent
            container_name: Portainer-agent
            volumes: 
                - /var/lib/docker/volumes:/var/lib/docker/volumes
                - /var/run/docker.sock:/var/run/docker.sock
            ports:
                - 9111:9001
            restart: always